import Head from "next/head";
import Cart from "@/components/cart";
import Product from "@/components/Product";
const ShoppingCart = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Cart/>
            <Product/>
            
        </>
    );
}
export default ShoppingCart;