import Head from "next/head";
import Navbar from "../components/navbar";
import Header from "../components/header";
import Featured from "../components/featured";
import Categories from "../components/cteagories";
import Footer from "../components/footer";

const Home = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <Header/>
            <Categories/>
            <Featured/>
            <Footer/>
        </>
    );
}

export default Home;
