
import Orderpage from "@/components/orderpage";
import Head from "next/head";
const OrderPage = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Orderpage/>
            
        </>
    );
}
export default OrderPage;