import Placeorder from "@/components/placeorder";
import Head from "next/head";
const PlaceOrder = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Placeorder/>
            
        </>
    );
}
export default PlaceOrder;