import Head from "next/head";
import Breadcrumb from "@/components/shop/breadcrumb";

export default function Home() {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Breadcrumb/>
            <div class="container-fluid">
                <div class="row px-xl-5">
                    <sidebar/>
                    <product/>     
                </div>   
            </div>
        </>
    );
}
