import Head from "next/head";
import Breadcrumb from "@/components/shop/breadcrumb";
import Sidebar from "@/components/shop/sidebar";
import Products from "@/components/shop/product";

const Shop = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Breadcrumb/>
            <div className="container-fluid">
                <div className="row px-xl-5">
                    <Sidebar/>
                    <Products/>     
                </div>   
            </div>
        </>
    );
}

export default Shop;