import LogIn from "@/components/signin";
import Head from "next/head";
import SignIn from "@/components/signin";
const Signin = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <SignIn/>
        </>
    );
}
export default Signin;