import SignUp from "@/components/signup";
import Head from "next/head";

const Signup = () => {
    return (
        <>
            <Head>
                <title>Departmental Store</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <SignUp/>


        </>
    );
}
export default Signup;